ARG BASEIMG=docker.io/ubuntu:22.04
FROM $BASEIMG

RUN (echo "/opt/view/lib" \
  && echo "/opt/view/lib64") > /etc/ld.so.conf.d/spack.conf

COPY bin/fix_spack_install /usr/local/bin/fix_spack_install

# Workaround for NVIDIA driver mismatch
ENV NVIDIA_DISABLE_REQUIRE=true

# The entrypoint ["/bin/bash", "--rcfile", "/etc/profile", "-l", "-c"]
# does not work in the container engine on Santis.
# We use ["/entrypoint.sh"] as a workaround
#ENTRYPOINT ["/bin/bash", "--rcfile", "/etc/profile", "-l", "-c"]
COPY docker/entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/bin/bash"]
SHELL ["/bin/bash", "--rcfile", "/etc/profile", "-l", "-c"]
