#!/bin/bash

#SBATCH --job-name="diffusion_mpi"
#SBATCH --ntasks=1            # total number of GPUs
#SBATCH --ntasks-per-node=1   # 1 MPI ranks per node
#SBATCH --account=csstaff
#SBATCH --hint=nomultithread  
#SBATCH --uenv=prgenv-gnu/24.11:v2
#SBATCH --view=default
#SBATCH --gpus-per-task=1

export MPICH_GPU_SUPPORT_ENABLED=1
export FI_CXI_RX_MATCH_MODE=software
export MPICH_RDMA_ENABLED_CUDA=1

srun ./mps-wrapper.sh /MY/PATH/TO/EXAMPLES/practicals/diffusion/diffusion2d_mpi 25 10000