include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build
  - test

variables:
  PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/rjanalik/test-spack0.20.1-cuda-ss:$CI_COMMIT_SHORT_SHA

build_job:
  stage: build
  extends: .container-builder
  variables:
    DOCKERFILE: ci/docker/Dockerfile.build

test_job:
  stage: test
  extends: .container-runner-hohgant-a100
  image: $PERSIST_IMAGE_NAME
  script:
    - cd /cuda_solutions/axpy/
    - echo asdf
    - env
    - echo qwer
    - ./axpy
    - ./axpy 28
    - ./axpy 29
    - ./axpy 30
    - echo "Let's make it time out"
    - sleep 1500
    - echo "The job should be killed before this"
  variables:
    SLURM_JOB_NUM_NODES: 1
    #SLURM_PARTITION: debug
    SLURM_NTASKS: 1
