include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - configure
  - run

pipeline-configure:
  stage: configure
  extends: .container-runner-lightweight-zen2
  image: docker.io/rjanalik/ci-generator:python-3.12.3
  script:
    - ci/ci-generator.py > pipeline.yml
  artifacts:
    paths:
      - pipeline.yml

generated-pipeline:
  stage: run
  trigger:
    include:
      - artifact: pipeline.yml
        job: pipeline-configure
    forward:
      pipeline_variables: true
    strategy: depend
