include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build
  - test

variables:
  PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/rjanalik/test-spack0.20.2-rocm5.6.1:$CI_COMMIT_SHORT_SHA

build_job:
  stage: build
  extends: .container-builder
  variables:
    DOCKERFILE: ci/docker/Dockerfile.build

test_job:
  stage: test
  extends: .container-runner-hohgant-mi200
  image: $PERSIST_IMAGE_NAME
  script:
    - pwd
    - ls -l
    - cat script*
    - cd /
    - ls
    - rocm-smi
    - ./stream
    - make -B
    - ./stream
  variables:
    SLURM_JOB_NUM_NODES: 1
      #SLURM_PARTITION: debug
    SLURM_NTASKS: 1
