include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build
  - test

variables:
  PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/helloworld:$CI_COMMIT_SHORT_SHA

build_job:
  stage: build
  extends: .uenv-runner-daint-gh200
  image: prgenv-gnu/25.6:v2
  script:
    - pwd
    - which g++
    - g++ --version
    - which cmake
    - cmake --version
    - uenv status
    - mkdir build
    - cd build
    - cmake ..
    - make
  variables:
    WITH_UENV_VIEW: 'default'
  artifacts:
    paths:
      - build/

test_job:
  stage: test
  extends: .uenv-runner-daint-gh200
  image: prgenv-gnu/25.6:v2
  script:
    - pwd
    - which g++
    - uenv status
    - ./build/hello
  variables:
    WITH_UENV_VIEW: 'default'
    SLURM_JOB_NUM_NODES: 2
    SLURM_PARTITION: debug
    SLURM_NTASKS: 2
