include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build
  - test

variables:
  PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/mpi_test:$CI_COMMIT_SHORT_SHA

build_job:
  stage: build
  extends: .container-builder
  variables:
    DOCKERFILE: ci/docker/Dockerfile.build

test_job:
  stage: test
  extends: .container-runner-eiger-mc
  image: $PERSIST_IMAGE_NAME
  script:
    - /src/hello
  variables:
    SLURM_JOB_NUM_NODES: 2
    SLURM_PARTITION: debug
    SLURM_NTASKS: 2
